package ui.appointments;

import app.controllers.AppointmentController;
import domain.Appointment;
import domain.User;
import domain.time.Time;
import javafx.geometry.Insets;
import javafx.scene.control.DatePicker;
import javafx.scene.control.Label;
import javafx.scene.control.TextField;
import javafx.scene.layout.GridPane;

/**
 * AppointmentInfoForm contains the fields for adding or updating a Appointment.
 */
public class AppointmentInfoForm extends GridPane {
    private static User currentUser = null;

    private static Appointment appointment = null;

    private static final TextField appointmentIdField = new TextField();
    private static final TextField appointmentTitleField = new TextField();
    private static final TextField appointmentDescriptionField = new TextField();
    private static final TextField appointmentLocationField = new TextField();
    // TODO: Add the contact controller.
    //private static final ContactComboBox contactComboBox = new ContactComboBox();
    private static final TextField appointmentTypeField = new TextField();
    // TODO: Add time comboBoxes
    private static final DatePicker startDatePicker = new DatePicker();
    private static final DatePicker endTimeComboBox = new DatePicker();
    //private static final ComboBox<Customer> customerComboBox = new ComboBox<>();
    // TODO: Add the user controller.
    //private static final UserComboBox userComboBox = new UserComboBox();


    /**
     * Constructs a new AppointmentInfoForm for use in the UI.
     */
    public AppointmentInfoForm(User currentUser) {
        AppointmentInfoForm.currentUser = currentUser;

        if (AppointmentInfoForm.appointment != null) {
            AppointmentInfoForm.appointment = new Appointment(AppointmentController.maxId() + 1);
        }

        Label appointmentId = new Label("ID (autogenerated)");
        this.add(appointmentId, 0, 0);
        appointmentIdField.setText(String.valueOf(appointment.getAppointmentId()));
        appointmentIdField.setDisable(true);
        this.add(appointmentIdField, 1, 0);

        Label appointmentName = new Label("Title");
        this.add(appointmentName, 0, 1);
        appointmentTitleField.setText(appointment.getTitle());
        this.add(appointmentTitleField, 1, 1);

        Label appointmentPhone = new Label("Description");
        this.add(appointmentPhone, 0, 2);
        appointmentDescriptionField.setText(appointment.getDescription());
        this.add(appointmentDescriptionField, 1, 2);

        Label appointmentAddress = new Label("Location");
        this.add(appointmentAddress, 0, 3);
        appointmentLocationField.setText(appointment.getLocation());
        this.add(appointmentLocationField, 1, 3);

        Label appointmentContactLabel = new Label("Contact");
        this.add(appointmentContactLabel, 0, 4);
        //appointmentTypeField.setText(appointment.getContactId());
        //this.add(appointmentTypeField, 1, 4);

        Label appointmentTypeLabel = new Label("Type");
        this.add(appointmentTypeLabel, 0, 5);
        appointmentTypeField.setText(appointment.getType());
        this.add(appointmentTypeField, 1, 5);

        Label startDateLabel = new Label("Start Date");
        this.add(startDateLabel, 0, 6);
        this.add(startDatePicker, 1, 6);

        Label endDateLabel = new Label("End Date");
        this.add(endDateLabel, 0, 8);
        this.add(startDatePicker, 1, 8);

        this.setPadding(new Insets(10, 10, 10, 10));
        this.setHgap(10);
        this.setVgap(10);
    }

    /**
     * sets the appointment to populate the form with.
     *
     * @param appointment the appointment to use
     */
    public static void setAppointment(Appointment appointment) {
        AppointmentInfoForm.appointment = appointment;
    }

    /**
     * clears the appointmentView to prevent data carryover.
     */
    public static void clearAppointmentView() {
        AppointmentInfoForm.appointment = null;
    }

    /**
     * @return the Appointment populated with the information stored in the form.
     */
    public static Appointment getAppointmentFromForm() {
        Appointment a = new Appointment(Integer.parseInt(appointmentIdField.getText()));
        //if (countryComboBox.getSelectionModel().getSelectedItem() == null) {
        //    Alerts.Warning("No Country Selected");
        //    return null;
        //}
        //if (firstLevelDivisionComboBox.getSelectionModel().getSelectedItem() != null) {
        //    a.setDivisionId(firstLevelDivisionComboBox.getValue().getId());
        //} else {
        //    Alerts.Warning("No First Level Division Selected");
        //    return null;
        //}
        if (a.getCreateDate() != null) {
            a.setCreateDate(a.getCreateDate());
        } else {
            a.setCreateDate(new Time());
        }
        if (a.getCreatedBy() != null) {
            a.setCreatedBy(a.getCreatedBy());
        } else {
            a.setCreatedBy(currentUser.getUserName());
        }
        if (a.getLastUpdate() != null) {
            a.setLastUpdate(a.getLastUpdate());
        } else {
            a.setLastUpdate(new Time());
        }
        a.setTitle(appointmentTitleField.getText());
        a.setDescription(appointmentDescriptionField.getText());
        a.setLocation(appointmentLocationField.getText());
        a.setType(appointmentTypeField.getText());
        a.setLastUpdatedBy(currentUser.getUserName());
        return a;
    }
}
